### ISSUE TITLE
Front-End: Responsive Checkout Page

### ISSUE THREAD

**Issue by kbonneteau** [kbonneteau/audiophile-ecommerce#8]
**Tasks:**

- [x] Create controlled form
- [x] Add placeholder details
- [x] Create regexp for form validation
- [x] Add dynamic validation & error messages
